In [76]:
import pandas as pd

df = pd.read_csv("homeprices (2).csv")

df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [77]:
dummies = pd.get_dummies(df.town,dtype=int)

In [78]:
df2 = pd.concat([df,dummies],axis='columns')

In [79]:
df2

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [80]:
df2 = df2.drop(['town','west windsor'],axis='columns')

In [81]:
df2

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [82]:
from sklearn import linear_model

reg = linear_model.LinearRegression()



In [83]:
X = df2.drop('price',axis='columns')

In [84]:
reg.fit(X,df2.price)

LinearRegression()

In [85]:
reg.predict([[2800,0,1]])

C:\Users\thang\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [86]:
reg.score(X,df2.price)


0.9573929037221873

In [87]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [88]:
dfle = df

dfle.town = le.fit_transform(dfle.town)

In [89]:
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [90]:
X2 = dfle[['town','area']].values

X2

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [91]:
y2 = dfle['price'].values

y2

X2

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [92]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer



ohe = ColumnTransformer([('encoder', OneHotEncoder(), [0])],     remainder='passthrough')

In [93]:
X2 = ohe.fit_transform(X2)

In [94]:
import numpy as np

X2 = np.array(X2)

In [95]:
X2 = X2[:,1:]

In [96]:
X2

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [97]:
REG = linear_model.LinearRegression()

In [98]:
REG.fit(X2,y2)

LinearRegression()

In [99]:
REG.predict([[1,0,2800]])

array([590775.63964739])

In [100]:
exdf = pd.read_csv('carprices.csv')
exdf

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [101]:
dosho = pd.get_dummies(exdf['Car Model'],dtype='int')

In [102]:
newdfo = pd.concat([exdf,dosho],axis='columns')

In [103]:
newdfo = newdfo.drop(['Car Model','Audi A5'],axis='columns')

In [118]:
newdfo


xo = newdfo.drop('Sell Price($)',axis='columns')

xo

newdfo

Mileage  Sell Price($)  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000          18000         6       1                      0
1     35000          34000         3       1                      0
2     57000          26100         5       1                      0
3     22500          40000         2       1                      0
4     46000          31500         4       1                      0
5     59000          29400         5       0                      0
6     52000          32000         5       0                      0
7     72000          19300         6       0                      0
8     91000          12000         8       0                      0
9     67000          22000         6       0                      1
10    83000          20000         7       0                      1
11    79000          21000         7       0                      1
12    59000          33000         5       0                      1

In [106]:
modo = linear_model.LinearRegression()

In [112]:
modo.fit(xo,newdfo['Sell Price($)'])

LinearRegression()

In [120]:
modo.predict([[59000,5,0,1]])

C:\Users\thang\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([30477.15426156])

In [122]:
modo.predict([[45000,4,0,0]])

C:\Users\thang\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([34537.77647335])

In [124]:
modo.predict([[86000,7,0,1]])

C:\Users\thang\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([17818.95045785])

In [128]:
modo.score(xo,newdfo['Sell Price($)'])

0.9417050937281082